/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests/index'
import { Route as ToolsBgRemoverRouteImport } from './routes/tools/bg-remover'
import { Route as GamesSnekRouteImport } from './routes/games/snek'
import { Route as AuthedPostsRouteImport } from './routes/_authed/posts'
import { Route as ToolsCopiumIndexRouteImport } from './routes/tools/copium/index'
import { Route as ToolsBingoIndexRouteImport } from './routes/tools/bingo/index'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts.index'
import { Route as ToolsBingoCreateRouteImport } from './routes/tools/bingo/create'
import { Route as AuthedProfileSplatRouteImport } from './routes/_authed/profile.$'
import { Route as AuthedPostsPostIdRouteImport } from './routes/_authed/posts.$postId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBgRemoverRoute = ToolsBgRemoverRouteImport.update({
  id: '/tools/bg-remover',
  path: '/tools/bg-remover',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSnekRoute = GamesSnekRouteImport.update({
  id: '/games/snek',
  path: '/games/snek',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPostsRoute = AuthedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthedRoute,
} as any)
const ToolsCopiumIndexRoute = ToolsCopiumIndexRouteImport.update({
  id: '/tools/copium/',
  path: '/tools/copium/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBingoIndexRoute = ToolsBingoIndexRouteImport.update({
  id: '/tools/bingo/',
  path: '/tools/bingo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostsRoute,
} as any)
const ToolsBingoCreateRoute = ToolsBingoCreateRouteImport.update({
  id: '/tools/bingo/create',
  path: '/tools/bingo/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileSplatRoute = AuthedProfileSplatRouteImport.update({
  id: '/profile/$',
  path: '/profile/$',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsPostIdRoute = AuthedPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthedPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof AuthedPostsRouteWithChildren
  '/games/snek': typeof GamesSnekRoute
  '/tools/bg-remover': typeof ToolsBgRemoverRoute
  '/tests/': typeof TestsIndexRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/profile/$': typeof AuthedProfileSplatRoute
  '/tools/bingo/create': typeof ToolsBingoCreateRoute
  '/posts/': typeof AuthedPostsIndexRoute
  '/tools/bingo/': typeof ToolsBingoIndexRoute
  '/tools/copium/': typeof ToolsCopiumIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/snek': typeof GamesSnekRoute
  '/tools/bg-remover': typeof ToolsBgRemoverRoute
  '/tests': typeof TestsIndexRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/profile/$': typeof AuthedProfileSplatRoute
  '/tools/bingo/create': typeof ToolsBingoCreateRoute
  '/posts': typeof AuthedPostsIndexRoute
  '/tools/bingo': typeof ToolsBingoIndexRoute
  '/tools/copium': typeof ToolsCopiumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/posts': typeof AuthedPostsRouteWithChildren
  '/games/snek': typeof GamesSnekRoute
  '/tools/bg-remover': typeof ToolsBgRemoverRoute
  '/tests/': typeof TestsIndexRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/_authed/profile/$': typeof AuthedProfileSplatRoute
  '/tools/bingo/create': typeof ToolsBingoCreateRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
  '/tools/bingo/': typeof ToolsBingoIndexRoute
  '/tools/copium/': typeof ToolsCopiumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/games/snek'
    | '/tools/bg-remover'
    | '/tests/'
    | '/posts/$postId'
    | '/profile/$'
    | '/tools/bingo/create'
    | '/posts/'
    | '/tools/bingo/'
    | '/tools/copium/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/snek'
    | '/tools/bg-remover'
    | '/tests'
    | '/posts/$postId'
    | '/profile/$'
    | '/tools/bingo/create'
    | '/posts'
    | '/tools/bingo'
    | '/tools/copium'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/posts'
    | '/games/snek'
    | '/tools/bg-remover'
    | '/tests/'
    | '/_authed/posts/$postId'
    | '/_authed/profile/$'
    | '/tools/bingo/create'
    | '/_authed/posts/'
    | '/tools/bingo/'
    | '/tools/copium/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  GamesSnekRoute: typeof GamesSnekRoute
  ToolsBgRemoverRoute: typeof ToolsBgRemoverRoute
  TestsIndexRoute: typeof TestsIndexRoute
  ToolsBingoCreateRoute: typeof ToolsBingoCreateRoute
  ToolsBingoIndexRoute: typeof ToolsBingoIndexRoute
  ToolsCopiumIndexRoute: typeof ToolsCopiumIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/bg-remover': {
      id: '/tools/bg-remover'
      path: '/tools/bg-remover'
      fullPath: '/tools/bg-remover'
      preLoaderRoute: typeof ToolsBgRemoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/snek': {
      id: '/games/snek'
      path: '/games/snek'
      fullPath: '/games/snek'
      preLoaderRoute: typeof GamesSnekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/posts': {
      id: '/_authed/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/tools/copium/': {
      id: '/tools/copium/'
      path: '/tools/copium'
      fullPath: '/tools/copium/'
      preLoaderRoute: typeof ToolsCopiumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/bingo/': {
      id: '/tools/bingo/'
      path: '/tools/bingo'
      fullPath: '/tools/bingo/'
      preLoaderRoute: typeof ToolsBingoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedPostsRoute
    }
    '/tools/bingo/create': {
      id: '/tools/bingo/create'
      path: '/tools/bingo/create'
      fullPath: '/tools/bingo/create'
      preLoaderRoute: typeof ToolsBingoCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile/$': {
      id: '/_authed/profile/$'
      path: '/profile/$'
      fullPath: '/profile/$'
      preLoaderRoute: typeof AuthedProfileSplatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdRouteImport
      parentRoute: typeof AuthedPostsRoute
    }
  }
}

interface AuthedPostsRouteChildren {
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedPostsRouteChildren: AuthedPostsRouteChildren = {
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedPostsRouteWithChildren = AuthedPostsRoute._addFileChildren(
  AuthedPostsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedPostsRoute: typeof AuthedPostsRouteWithChildren
  AuthedProfileSplatRoute: typeof AuthedProfileSplatRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedPostsRoute: AuthedPostsRouteWithChildren,
  AuthedProfileSplatRoute: AuthedProfileSplatRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  GamesSnekRoute: GamesSnekRoute,
  ToolsBgRemoverRoute: ToolsBgRemoverRoute,
  TestsIndexRoute: TestsIndexRoute,
  ToolsBingoCreateRoute: ToolsBingoCreateRoute,
  ToolsBingoIndexRoute: ToolsBingoIndexRoute,
  ToolsCopiumIndexRoute: ToolsCopiumIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
