/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests/index'
import { Route as HylIndexRouteImport } from './routes/hyl/index'
import { Route as GenshinIndexRouteImport } from './routes/genshin/index'
import { Route as CopiumIndexRouteImport } from './routes/copium/index'
import { Route as BingoIndexRouteImport } from './routes/bingo/index'
import { Route as BgRemoverIndexRouteImport } from './routes/bg-remover/index'
import { Route as GamesSnekRouteImport } from './routes/games/snek'
import { Route as BingoCreateRouteImport } from './routes/bingo/create'
import { Route as AuthedPostsRouteImport } from './routes/_authed/posts'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts.index'
import { Route as GenshinProfilesIdRouteImport } from './routes/genshin/profiles.$id'
import { Route as GenshinCharactersIdRouteImport } from './routes/genshin/characters.$id'
import { Route as AuthedProfileSplatRouteImport } from './routes/_authed/profile.$'
import { Route as AuthedPostsPostIdRouteImport } from './routes/_authed/posts.$postId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const HylIndexRoute = HylIndexRouteImport.update({
  id: '/hyl/',
  path: '/hyl/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenshinIndexRoute = GenshinIndexRouteImport.update({
  id: '/genshin/',
  path: '/genshin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CopiumIndexRoute = CopiumIndexRouteImport.update({
  id: '/copium/',
  path: '/copium/',
  getParentRoute: () => rootRouteImport,
} as any)
const BingoIndexRoute = BingoIndexRouteImport.update({
  id: '/bingo/',
  path: '/bingo/',
  getParentRoute: () => rootRouteImport,
} as any)
const BgRemoverIndexRoute = BgRemoverIndexRouteImport.update({
  id: '/bg-remover/',
  path: '/bg-remover/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSnekRoute = GamesSnekRouteImport.update({
  id: '/games/snek',
  path: '/games/snek',
  getParentRoute: () => rootRouteImport,
} as any)
const BingoCreateRoute = BingoCreateRouteImport.update({
  id: '/bingo/create',
  path: '/bingo/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPostsRoute = AuthedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostsRoute,
} as any)
const GenshinProfilesIdRoute = GenshinProfilesIdRouteImport.update({
  id: '/genshin/profiles/$id',
  path: '/genshin/profiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GenshinCharactersIdRoute = GenshinCharactersIdRouteImport.update({
  id: '/genshin/characters/$id',
  path: '/genshin/characters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileSplatRoute = AuthedProfileSplatRouteImport.update({
  id: '/profile/$',
  path: '/profile/$',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsPostIdRoute = AuthedPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthedPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof AuthedPostsRouteWithChildren
  '/bingo/create': typeof BingoCreateRoute
  '/games/snek': typeof GamesSnekRoute
  '/bg-remover/': typeof BgRemoverIndexRoute
  '/bingo/': typeof BingoIndexRoute
  '/copium/': typeof CopiumIndexRoute
  '/genshin/': typeof GenshinIndexRoute
  '/hyl/': typeof HylIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/profile/$': typeof AuthedProfileSplatRoute
  '/genshin/characters/$id': typeof GenshinCharactersIdRoute
  '/genshin/profiles/$id': typeof GenshinProfilesIdRoute
  '/posts/': typeof AuthedPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bingo/create': typeof BingoCreateRoute
  '/games/snek': typeof GamesSnekRoute
  '/bg-remover': typeof BgRemoverIndexRoute
  '/bingo': typeof BingoIndexRoute
  '/copium': typeof CopiumIndexRoute
  '/genshin': typeof GenshinIndexRoute
  '/hyl': typeof HylIndexRoute
  '/tests': typeof TestsIndexRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/profile/$': typeof AuthedProfileSplatRoute
  '/genshin/characters/$id': typeof GenshinCharactersIdRoute
  '/genshin/profiles/$id': typeof GenshinProfilesIdRoute
  '/posts': typeof AuthedPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/posts': typeof AuthedPostsRouteWithChildren
  '/bingo/create': typeof BingoCreateRoute
  '/games/snek': typeof GamesSnekRoute
  '/bg-remover/': typeof BgRemoverIndexRoute
  '/bingo/': typeof BingoIndexRoute
  '/copium/': typeof CopiumIndexRoute
  '/genshin/': typeof GenshinIndexRoute
  '/hyl/': typeof HylIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/_authed/profile/$': typeof AuthedProfileSplatRoute
  '/genshin/characters/$id': typeof GenshinCharactersIdRoute
  '/genshin/profiles/$id': typeof GenshinProfilesIdRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/bingo/create'
    | '/games/snek'
    | '/bg-remover/'
    | '/bingo/'
    | '/copium/'
    | '/genshin/'
    | '/hyl/'
    | '/tests/'
    | '/posts/$postId'
    | '/profile/$'
    | '/genshin/characters/$id'
    | '/genshin/profiles/$id'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bingo/create'
    | '/games/snek'
    | '/bg-remover'
    | '/bingo'
    | '/copium'
    | '/genshin'
    | '/hyl'
    | '/tests'
    | '/posts/$postId'
    | '/profile/$'
    | '/genshin/characters/$id'
    | '/genshin/profiles/$id'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/posts'
    | '/bingo/create'
    | '/games/snek'
    | '/bg-remover/'
    | '/bingo/'
    | '/copium/'
    | '/genshin/'
    | '/hyl/'
    | '/tests/'
    | '/_authed/posts/$postId'
    | '/_authed/profile/$'
    | '/genshin/characters/$id'
    | '/genshin/profiles/$id'
    | '/_authed/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  BingoCreateRoute: typeof BingoCreateRoute
  GamesSnekRoute: typeof GamesSnekRoute
  BgRemoverIndexRoute: typeof BgRemoverIndexRoute
  BingoIndexRoute: typeof BingoIndexRoute
  CopiumIndexRoute: typeof CopiumIndexRoute
  GenshinIndexRoute: typeof GenshinIndexRoute
  HylIndexRoute: typeof HylIndexRoute
  TestsIndexRoute: typeof TestsIndexRoute
  GenshinCharactersIdRoute: typeof GenshinCharactersIdRoute
  GenshinProfilesIdRoute: typeof GenshinProfilesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hyl/': {
      id: '/hyl/'
      path: '/hyl'
      fullPath: '/hyl/'
      preLoaderRoute: typeof HylIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genshin/': {
      id: '/genshin/'
      path: '/genshin'
      fullPath: '/genshin/'
      preLoaderRoute: typeof GenshinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copium/': {
      id: '/copium/'
      path: '/copium'
      fullPath: '/copium/'
      preLoaderRoute: typeof CopiumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bingo/': {
      id: '/bingo/'
      path: '/bingo'
      fullPath: '/bingo/'
      preLoaderRoute: typeof BingoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bg-remover/': {
      id: '/bg-remover/'
      path: '/bg-remover'
      fullPath: '/bg-remover/'
      preLoaderRoute: typeof BgRemoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/snek': {
      id: '/games/snek'
      path: '/games/snek'
      fullPath: '/games/snek'
      preLoaderRoute: typeof GamesSnekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bingo/create': {
      id: '/bingo/create'
      path: '/bingo/create'
      fullPath: '/bingo/create'
      preLoaderRoute: typeof BingoCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/posts': {
      id: '/_authed/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedPostsRoute
    }
    '/genshin/profiles/$id': {
      id: '/genshin/profiles/$id'
      path: '/genshin/profiles/$id'
      fullPath: '/genshin/profiles/$id'
      preLoaderRoute: typeof GenshinProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genshin/characters/$id': {
      id: '/genshin/characters/$id'
      path: '/genshin/characters/$id'
      fullPath: '/genshin/characters/$id'
      preLoaderRoute: typeof GenshinCharactersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile/$': {
      id: '/_authed/profile/$'
      path: '/profile/$'
      fullPath: '/profile/$'
      preLoaderRoute: typeof AuthedProfileSplatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdRouteImport
      parentRoute: typeof AuthedPostsRoute
    }
  }
}

interface AuthedPostsRouteChildren {
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedPostsRouteChildren: AuthedPostsRouteChildren = {
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedPostsRouteWithChildren = AuthedPostsRoute._addFileChildren(
  AuthedPostsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedPostsRoute: typeof AuthedPostsRouteWithChildren
  AuthedProfileSplatRoute: typeof AuthedProfileSplatRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedPostsRoute: AuthedPostsRouteWithChildren,
  AuthedProfileSplatRoute: AuthedProfileSplatRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  BingoCreateRoute: BingoCreateRoute,
  GamesSnekRoute: GamesSnekRoute,
  BgRemoverIndexRoute: BgRemoverIndexRoute,
  BingoIndexRoute: BingoIndexRoute,
  CopiumIndexRoute: CopiumIndexRoute,
  GenshinIndexRoute: GenshinIndexRoute,
  HylIndexRoute: HylIndexRoute,
  TestsIndexRoute: TestsIndexRoute,
  GenshinCharactersIdRoute: GenshinCharactersIdRoute,
  GenshinProfilesIdRoute: GenshinProfilesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
